### ISSUE TITLE
Vb.Net

### ISSUE THREAD

**Issue by johnkenalcantara** [MxLabs/Anviz#16]
Do you have vb.Net sample how to use this? How to download new records.

**Comment by JohnKiller** [comment]
Hi,
Currently we don't provide a VB.Net sample, however code is very simple to translate. This should get you started:

    Imports Anviz.SDK

    Public Class Form1
        Private Async Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
            Dim manager As New AnvizManager(0)
            Using device = Await manager.Connect("10.0.0.1")
                Dim employees As New Dictionary(Of ULong, String)
                For Each emp In Await device.GetEmployeesData()
                    employees.Add(emp.Id, emp.Name)
                Next
                For Each stamp In Await device.DownloadRecords(False) 'True to get only new records
                    Dim employeeName = employees(stamp.UserCode)
                    Dim recordDate = stamp.DateTime
                    MsgBox(employeeName & " at " & recordDate)
                Next
            End Using
        End Sub
    End Class

**Comment by johnkenalcantara** [comment]
Thanks, working already but only the download new record. Download all record does not work. Im using W1.

Now working in EP300.

**Comment by JohnKiller** [comment]
Does the included c# sample work for you? Can you try cloning the latest development branch and see if it works? Thanks

**Comment by johnkenalcantara** [comment]
Yes tried cloning it, only the download new record is working. Download all does not work.

**Comment by MxLabs** [comment]
If you can download new records, you should be able to download all records. Can you write the returned data here?

**Comment by johnkenalcantara** [comment]
Hot to do it? 
When i checked the records variable it return null value.

**Comment by johnkenalcantara** [comment]
Connected to device W1 ID 11 SN 0640100017200116
Current device time is 8/22/2019 6:23 AM
Device IP is 192.168.0.222 255.255.255.0 192.168.0.1 08-00-0F-06-37-27 mode is Server
Employee 1 ->  pwd  card  fp RightThumb
-> RightThumb GxkVVcEbIlehIAwUYTahGME8GCzBUyBcgVSxXwFiHCJBdihjoRwbrGIrnVYiLSfDIjylw6JFG5jCR4XRokqxhkJLKZyiT6CD4lQF5aJXGesCXpilQmWN5IJlk6SCZpZPAmmZZGJzCw4icxcOwgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABsUmVWhIR8WgSEjQAE0pZiBUTWfYVUk3KFdnuLhYoWOgWUfoqF1q+OhF5/sQhelluIdj9NiJ6FWgiksg2I4nmxCOqrDgkUKEeJFoJjiSa3cYlClA+JRCmbCWR5AQmWRZQJnGk5Capzkom8OzwIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtdg=
Employee 2 ->  pwd  card  fp RightThumb, RightIndex
-> RightThumb ECGmLCE9r9shQxRlgVMkoyFWHCQBdx9hwSSs2IIskeeiMKeWIjmvw4JDoZMiTiYeYlUo4GJlrSCCZyghom8tS4IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8TnewBGqSZgSIfGMFFrR9BbZpLwS4lg+Ixo5vCNhbTwkaQJCJGp98iR5ygwkmriOJZoCDiWxuiImWgiqJvLUuCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtdg=
-> RightIndex FhATFKEbk6pBHibDISORKMElm1hBJaWbYS0hA4ExE5OBSw0OIVwo4ME8C2WiPBUUAjwiHaI8mVuCSJTkYkmcB4JMoOCiV50iAmQL4kJwkguCcY9KAniTDqIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYVFuqBGSiCoR8fGAEfKNuBJqSDQUMQTqFEGWIhSaSgYVkroYFhlc2hZpONwSqV0oI1DqXCNZhUAjYc26I2pZ5iQ59H4kWdIQJRoCLiXI5iImuRi2J1IeOCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtdg=
Employee 4 ->  pwd  card  fp
Employee 222 ->  pwd  card  fp

**Comment by JohnKiller** [comment]
Try the new released version. The sample program outputs at this line

    Console.WriteLine($"TotalUsers {stats.UserAmount} TotalRecords {stats.AllRecordAmount}");

It should have the correct values

**Comment by JohnKiller** [comment]
I'm closing this issue, feel free to reopen it if your problem is not solved

**Comment by noelching** [comment]
What Features should i use if i want to disconnect? and how do i know if i was connected to device?

**Comment by JohnKiller** [comment]
AnvizDevice implementa IDisposable, so you need to dispose the object to disconnect. You cannot know if you are still connected or not, you can only sent commands and if they succeed then you are still connected

**Comment by noelching** [comment]
> AnvizDevice implementa IDisposable, so you need to dispose the object to disconnect. You cannot know if you are still connected or not, you can only sent commands and if they succeed then you are still connected

Does the Download Record in AnvizDevice is getting all records of attendance? 
I was trying to create it in VB.net
```
Dim records = Await device.DownloadRecords(True)
For Each rec In records
Dim uid As String
Dim datetotime As Date
Dim recordtype As String
Dim worktype As String

uid = dict(rec.UserCode)
datetotime = rec.DateTime.ToShortDateString() & " " & rec.DateTime.ToShortTimeString()
recordtype = rec.RecordType
worktype = rec.WorkType

                Dim newitem As New ListViewItem()

                newitem.Text = uid
                newitem.SubItems.Add(datetotime)
                newitem.SubItems.Add(recordtype)
                newitem.SubItems.Add(worktype)

                LvAll.Items.Add(newitem)
 Next
```

And what command should i use to go in `AnvizStream` to get the `Dispose`
