### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by JohnKiller** [MxLabs/Anviz#17]
So if I got this right, currently the continuous integration publishes a new nuget version for every pushed commit?

If so, I suggest creating another branch called "development" and merging when we are ready to ship a new version.

We should also use something like SemVer for version numbers and maybe a changelog.

What do you think?

**Comment by MxLabs** [comment]
> So if I got this right, currently the continuous integration publishes a new nuget version for every pushed commit?

You're right. The reason I added continuous integration was to quickly respond to users wishes.

> If so, I suggest creating another branch called "development" and merging when we are ready to ship a new version.

Yes, this is no longer avoidable.





> We should also use something like SemVer for version numbers and maybe a changelog.

If there are no new protocols, you're right. We can use.
