### ISSUE TITLE
RealTime support

### ISSUE THREAD

**Issue by jleal52** [MxLabs/Anviz#26]
Hello and thank you for the code, it works great!.

In the official SDK, there is a "CKT_ReadRealtimeClocking" with return all clocking records of real-time enabled devices. This method doesn't use the device ID, it for all connected devices.

I've not found that method in the Communication Protocol document, do you know how that method works? and how can it be implemented?.

Thank you.

**Comment by JohnKiller** [comment]
Can you explain in more detail how that mode works? In the `AdvancedSettings` class there is the field `bool RealTimeMode` which I have not yet investigated.

After you enable that, what happens? The device continuously sends new records by itself?

**Comment by jleal52** [comment]
Hello John, 

Yes I've been investigating the ethernet traffic and when you enable realtime, the device send clocking record continuosly.

I'm trying to wait for commands in the network stream, and yes, they arrive in realtime from the device.

This is the method I'm trying in AnvizDevice.cs:

```
public void DownloadRealTimeRecords(Action<ulong, Record> newRecord)`
        {
            th = new Thread(new ThreadStart(async () =>
            {
                while (DeviceStream.CanRead)
                {
                        var resp = await Response.FromStream(0xdf, DeviceStream);
                        Record rc = new Record(resp.DATA, 0);
                        newRecord(this.DeviceId, rc);
                }
            }));
            th.Start();
        }
```

It calls the newRecord delegate as the new records arrive.

The command received is 0xDF with the format that appears in the documentation.

**Comment by JohnKiller** [comment]
Thanks for sharing your code. At this time, the library isn't thread-safe, so what you did there will conflict when you try to send other commands. Also, the receiving code is highly coupled to the sending mechanism. I have to change the way we receive packets.

I'll be working on this once I'm done with the server side code, which currently I'm not happy at all.

**Comment by JohnKiller** [comment]
Hi, with the latest code from this repo, you can now read packets asynchronously.
Can you take a look and see if you can get real time support in this mode?
Thanks

**Comment by JohnKiller** [comment]
Hi @jleal52 did you have any time to work on this? Any help is appreciated.
Thanks

**Comment by JohnKiller** [comment]
I'm happy to annouce that this feature has been implemented!
