### ISSUE TITLE
VB.NET - How to specify connection Comm Pwd for connecting device from AnvizManager object ?

### ISSUE THREAD

**Issue by ECGITServices** [MxLabs/Anviz#27]
Hi All !!

How can I specify connection Comm Pwd for connecting device from AnvizManager object ? I'm searching about it but I haven't found any sample code or info about it.

I am trying to connect to 3 devices through a Public IP and ports (5010, 5011 and 5012) which is linked to the router in other distinct LAN to the LAN which I am connected.

I can connect the 3 devices through Crosschex Standard application without problem, but I need to access the devices to get the records from another application developed in vb.net. And that's where the problem is.
I think that the problem is located in the Comm PWD because I haven't found any property, parameter or method in the SDK to specify it when I run the AnvizManager.Connect method. I only can specify the IP and the port as parameters, but I can't specify the Comm PWD. So, the connection result is FAIL.

Could you help me with this issue, please?. 

Thanks so much All in advance.

Enrique.

**Comment by JohnKiller** [comment]
Hi Enrique,
Related #20, cmd is likely 0x04.
I will check and report to you soon.
Gianni

**Comment by JohnKiller** [comment]
Hi, I've implemented connection authentication. I've also updated the sample program to show how to use it.

**Comment by noelching** [comment]
How do i check if i was connected to device ?
