### ISSUE TITLE
How to Connect from Device through VB.net program?

### ISSUE THREAD

**Issue by noelching** [MxLabs/Anviz#29]
How do i connect to the device through program? it seem's the Await Operator doesn't working I'm really new into this language sorry for disturbance.

![Sample Error](https://user-images.githubusercontent.com/55343663/67743552-f6227f00-fa59-11e9-9cf5-6f9d439fdc25.png)

EDIT: I tried removing the Await operator and it works but I can't see the Device Ping and Receive Packet

**Comment by JohnKiller** [comment]
Hi, take a look here: https://github.com/MxLabs/Anviz/issues/16#issuecomment-522542997

**Comment by noelching** [comment]
> Hi, take a look here: [#16 (comment)](https://github.com/MxLabs/Anviz/issues/16#issuecomment-522542997)

Hi, I've seeing feedback that this SDK doesn't work in EP300 , i haven't tried it yet.  I'm still confused how do i start it. 
And also I'm always having a problem in this Await operation 
Sorry for disturbing. 
![Error in Await](https://user-images.githubusercontent.com/55343663/67760788-ea947f80-fa7c-11e9-864b-8d4dbaa447d6.png)
