### ISSUE TITLE
Facepass 7 - EnrollFace Templates

### ISSUE THREAD

**Issue by xiltoos** [MxLabs/Anviz#30]
Hello, can you adapt this code to export and import users enroll face templates?

Thanks.

Gildo Soares

**Comment by JohnKiller** [comment]
Hi,
I currently don't have any device with face recognition.
You can start Wireshark and investigate the commands. Adding new commands to this library is straightforward.
I can help if you provide some TCP traces

**Comment by jtobia** [comment]
Hi,
I did have adapt anviz.sdk to work with a facepass7.
Thare are a very little changes to do for this.
The first is in the response class FromStream async method: buffer size >= 15360 (size of face template) and manage the partial read on anviz response when read the data part of the response.
Then i have add a Get/Set FaceTemplateCommand.
Thera are other adjustment to made but these is enough for working.
If you want in the coming days I could share my changes. Tell me how. In a new branch?

**Comment by JohnKiller** [comment]
Yes - fork the repo, work in the development branch and create a pull request.
Thanks

**Comment by JohnKiller** [comment]
Build 2.0.7 released
