### ISSUE TITLE
Partial Packet Fail

### ISSUE THREAD

**Issue by Mikec6162** [MxLabs/Anviz#37]
Hi, been using this SDK to communicate with 4 timeclocks, it works really well except when someone is clocking in at the same time the program tries to communicate with the clock (Either record download or user upload). It then locks up the program. If run in Visuals Studio it errors on Partial packet fail.
I converted and modified the sample program to Vb.net to fit in with an existing program. Not that familiar with C#.
Is there any way to  detect the clocks are busy or handle the error?

**Comment by JohnKiller** [comment]
Hi, are you using the latest nuget version?
The library has a timeout and should throw an exception that you can catch if the device is busy.
At this time, when this event occurs, the internal state of the `AnvizDevice` class cannot be trusted anymore so the underlying stream is closed and you must dispose the class.
In a future version, this will be handled by the `AnvizManager` class. The instance will hold all the connected devices and will raise events for when this things happens.

**Comment by Mikec6162** [comment]
Hi, thanks for the quick response.
I am using the latest version.
I have tried using catch/try to pick up any errors in the sub that's calling the SDK with no luck.
Would you possibly have an example of how to catch these errors? Thanks

**Comment by JohnKiller** [comment]
Hi,
There was in fact an exception that was being thrown inside the thread that is responsible for reading data from the device. You couldn't catch that.

I have exposed the DeviceError event in commit 8b941c5d3d39cce194e04303e54188e853b1cd57 (released on NuGet v2.0.8). Try now.

**Comment by Mikec6162** [comment]
Thanks Gianni, that has stopped the program from crashing, so now
hopefully I just need to manage the error and all should be good.
