### ISSUE TITLE
C2Pro

### ISSUE THREAD

**Issue by remerg** [MxLabs/Anviz#39]
Hello, 

I'm trying to connect to an anviz C2Pro and I'm getting connection fail.  In the Response class it throws me the "Invalid response" exception, the value of the RET field = RET_FAIL.

I installed the crosschex and it detects the machine without any problem.

Can you help me?

**Comment by JohnKiller** [comment]
Hi, I don't have the C2 so I can't do any test.
Can you provide a packet capture with WireShark of both the communication attempt of this library and the equivalent of CrossChex?

**Comment by remerg** [comment]
I can't install anything on the server and the machine is already installed on the client.

**Comment by JohnKiller** [comment]
Just pushed 2.0.9 to NuGet, please try this version. Thanks

**Comment by JohnKiller** [comment]
Closing this issue. Feel free to reply if you still need help
