### ISSUE TITLE
Fix for A300 (possibly EP300 too)

### ISSUE THREAD

**Issue by MicaelMor** [MxLabs/Anviz#40]
Hi,

With an anviz A300 the GetDeviceID method does not retrieve the correct value, and since the codebase expects GetDeviceID to get a correct device ID this cascades into the rest of the code making it unusable for these projects.

However the current code base is already able to get the correct DeviceID, since this can be found in the field response.DeviceID, but currently the code uses the field response.DATA, I do not know if making this change:

`DeviceId = Bytes.Read(response.DATA);`
to
`DeviceId = response.DeviceID;`

Would break compatibility with other anviz models, but it does fix the issue with the A300, which went from essentially not being able to do anything, to being able to do at least most of the things (haven't tested it all).

Assuming this does not break compatibility, and that there isn't a better way of doing this, would it be possible to have this changed committed to a new release?

Thank you.

**Comment by JohnKiller** [comment]
Hi,
Can you kindly test the current version on the development branch?
Thank you

**Comment by MicaelMor** [comment]
Hi,

Just tested it using the sample project and almost everything seems to work fine, with the exception of the following line:

> var id = await device.GetDeviceID();

Which sets the DeviceId back to the wrong value, so I had to ofc disable it or else all other commands would fail.

Thank you.
