### ISSUE TITLE
Get data from device when new enter or exit happened (attendance)

### ISSUE THREAD

**Issue by mostafaebrahimi** [MxLabs/Anviz#43]
Hi and thanks for your great library for Anviz
I'm using this library for Anviz P7
do you know a method or command to get data from device when attendance happened to device ?
(I'm getting this data for my own software and I'm not using Anviz crosschex at all.So I need to know when someone enter or exit)
The problem is that checking the device on interval and getting new records is not a good way because it's so time and resource wasting. if you know another way to handle this please tell me.
Thanks in advance

**Comment by JohnKiller** [comment]
Hi, what you need is real time support, which is tracked by #26 
Unfortunately, this feature is not yet implemented.

**Comment by mostafaebrahimi** [comment]
@JohnKiller 
I want to use another method for this problem
but for know I have another issue.
I'm new to `c#` and my main server is using `nodejs`.
for connecting to `Anviz` from `nodejs` I'm using `redis pubsub` and sending data through pubsub to `c#` and then get data and return to `nodejs`,But their is a problem that I can not connect to 
`Anviz device` in the handler of pubsub and I have to put all my code containing `new AnvizManager` and `manager.connect` into handler and for every request it's taking a long time to connect.
do you know anyway to handler it ?
this is my code:
```c#
using ServiceStack.Redis;
...
...

static async Task createRedisHost()
{
    var redisConsumer = new RedisClient("localhost:6379");
    var subscription  = redisConsumer.CreateSubscription();
....
    var manager = new AnvizManager();
    manager.ConnectionUser = "admin";
    manager.ConnectionPassword = "12345";
    manager.AuthenticateConnection = true;
    var mdevice = await manager.Connect(DEVICE_HOST);
    mdevice.DevicePing += (s, e) => Console.WriteLine("Device Ping Received");
    mdevice.ReceivedPacket += (s, e) => Console.WriteLine("Received packet");
    mdevice.DeviceError += (s, e) => throw e;
...
    subscription.OnSubscribe = channel =>
    {
        Console.WriteLine(String.Format("Subscribed to '{0}'", channel));
    };
    subscription.OnUnSubscribe = channel =>
    {
        Console.WriteLine(String.Format("UnSubscribed from '{0}'", channel));           
    };
    subscription.OnMessage = async (channel, msg) =>
    {
       Console.WriteLine(String.Format("Received '{0}' from channel '{1}'", msg, channel));
       await connectToAnviz(mdevice);
    }
    subscription.SubscribeToChannels("myChannel");
....
}
static async Task connectToAnviz(AnvizDevice mdevice)
{
    var res = await mdevice.GetDateTime();
    Console.WriteLine(Convert.ToString(res.DAY));
}
```

if you publish a single message (not important what's the message) on channel `myChannel` the method connectToAnviz will be fired but here u don't get any data.
if you transfer all following section to `connectToAnviz` method:
```c#
    var mdevice = await manager.Connect(DEVICE_HOST);
    mdevice.DevicePing += (s, e) => Console.WriteLine("Device Ping Received");
    mdevice.ReceivedPacket += (s, e) => Console.WriteLine("Received packet");
    mdevice.DeviceError += (s, e) => throw e;
```
then it will work.
I don't know what's the reason but I guess this is something related to `TCP` connection but I don't know why it's happening.
Thanks in advanced

**Comment by JohnKiller** [comment]
Hi, just pinging back to let you know that this feature is now available! Take a look at the example project
