### ISSUE TITLE
Some Doubts

### ISSUE THREAD

**Issue by alvarofguti** [MxLabs/Anviz#59]
I have some doubts regarding some functions of the SDK.

1. To retrieve the record types of a clock I am using the CChex_GetUserAttendanceStatusInfo function that if I don't understand the documentation wrong, it returns a structure of the type CCHEX_SET_USER_ATTENDANCE_STATUS_STRU. The variables fp_len and atten_status_number always arrive empty but it seems that those values ​​come in the variable data_info in positions 4 and 8, is it correct?
If this is so, is the data_info size 168 instead of 160? If they are 160 and the first 8 positions are to return the values ​​of fp_len and atten_status_number, it would be losing characters of the last type of record.

2. I have three different watches (A300, W1 and Facepass). When retrieving the record types of all of them to convert the byte array to a string we do it with Encoding.Default.GetString (result.data_info) .Replace ("\ 0", ""). In the case of the A300 it does well, but in the other two clocks characters appear after each type of registration. Is there any way to avoid it?

3. I need to dump the record types to clocks. For this I use the CChex_SetUserAttendanceStatusInfo function, but I have the same problem as before. If I encode the record types in the 160 positions of the data_info variable of the structure in the clocks strange characters appear. And if I do it from position 8 on the clocks, the record types do not appear.

4. When retrieving the users of the clocks with the CChex_ListPersonInfo function, in the structure that returns, how is the fp_status field interpreted? As I interpret in the documentation from 0 to 9 it would identify each fingerprint and 10 for faces, but when I am retrieving facepass users it comes as 1024, not 10. And I don't know how to interpret it when there are two fingerprints for the same user.

5. After dumping faces to the Facepass clock, the clock recognizes me but the fp_status field when recovering the users returns me to 0 and if I enter through the clock configuration to see the user does not seem to have registered any face and when calling the Cchex_DownloadFingerPrint function does not return anything. How do I have to dump faces to Facepass?

Thank you very much.

**Comment by JohnKiller** [comment]
Hi,
Your questions are about the official SDK. This is an open source alternative, sorry.
