### ISSUE TITLE
Basic Usage

### ISSUE THREAD

**Issue by Nachix2003** [MxLabs/Anviz#64]
Can someone explain to me the basics to run this library, take into account i do not know anything about C#.

I would really appreciate it.

**Comment by JohnKiller** [comment]
Hi, there is a complete example here: https://github.com/MxLabs/Anviz/tree/development/Sample

May I ask you why are you interested in a low lever library if you don't know the language it's written in? Maybe you need a complete program like CrossChex?

**Comment by Nachix2003** [comment]
Thank you, i made it work on a nodejs library.
