### ISSUE TITLE
AppVeyor build is broken :(

### ISSUE THREAD

**Issue by JohnKiller** [MxLabs/Anviz#66]
Hi @MxLabs,
How are you? :)
Sorry to bother you, but I think that the nuget build process is broken, and I don't have access to anything to fix this.
Maybe we could switch to GitHub actions?

**Comment by MxLabs** [comment]
Hey @JohnKiller, I am great thank you 😊 How about you?
Github actions are a good idea, I will make the change you want tonight.

**Comment by JohnKiller** [comment]
Doing great!
It looks like the action worked, it created a release! However the push to nuget may have failed?

**Comment by MxLabs** [comment]
Hey @JohnKiller I know this bug :) I need change the framework to .net framework.

**Comment by JohnKiller** [comment]
Uhm isn't there a way to keep .net core?

**Comment by MxLabs** [comment]
@JohnKiller Ok, we have solved the problem. It will be enough to create a label for the new version :)

**Comment by JohnKiller** [comment]
Thank you very much
