### ISSUE TITLE
Anviz A350C Card Reader

### ISSUE THREAD

**Issue by Fludem** [MxLabs/Anviz#76]
Hey,

I've used the library for a few years to communicate with a few hundred A350C's without problem.

I would have just made a PR for the Read me change, but I haven't tested alarms. 

I also didn't know if you'd like it to be listed as supported, as it's also a card scanner. So, a lot of the face functionality will, of course, not work.

**Comment by Fludem** [comment]
Really sorry, I also meant to say THANK YOU! :)

**Comment by JohnKiller** [comment]
Thanks for the kind words!

From the product specs, it looks like a normal card reader, without any face features, just like VF30, which we fully support.

So yes, if you would like to, open a PR and I will merge it
