### ISSUE TITLE
How do I get the Status of the Record

### ISSUE THREAD

**Issue by elmerrgarcia** [MxLabs/Anviz#84]
Your project is awesome,  I came to dead end and need your help, 
1. Can i only download time frame date? From - To
2. How can I know if the record is In/Out or other status.
Thank you.

**Comment by JohnKiller** [comment]
Hi,
1. Anviz devices stores time records in a list. The only correct way to read those records is to loop them and finally call `ClearNewRecords` so the next time you will get only the new ones. Then you will store this info in your own DB and do whaterver query you want
2. There is `RecordType` inside the `Record` class

**Comment by elmerrgarcia** [comment]
Im getting different values from record type 0,1, 128,129,135 can you explain these values i only need in and out
